# This file is rendered via JSON-e by
# - mozilla-taskcluster - https://docs.taskcluster.net/reference/integrations/mozilla-taskcluster/docs/taskcluster-yml
# - cron tasks - taskcluster/taskgraph/cron/decision.py
# - action tasks - taskcluster/taskgraph/actions/registry.py
---
version: 0
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes: []
    payload:
      maxRunTime: 600
      image: "ubuntu:16.04"

      command:
        - "/bin/bash"
        - "--login"
        - "-cxe"
        - >
          echo hello
    # Each task also requires explicit metadata
    metadata:
      name: "DeepSpeech Decision Task"
      description: "DeepSpeech Decision Task: triggers everything."
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
